blockmanager/urls.py
from django.conf.urls import patterns, url
from blockmanager import views


urlpatterns = patterns('',
		url(r'^$', views.index, name="index"),
		url(r'^createblock/$', views.create_block, name="create_block"),
		url(r'^get_vms/$', views.get_vms, name="get_vms"),
		url(r'^mount/$', views.mount, name="mount"),
		url(r'^umount/$', views.umount, name="umount"),
		url(r'^delete/$', views.delete, name="delete"),
		url(r'^search/$', views.search, name="search"),
		url(r'^import/$', views.import_block, name="import"),
		url(r'^login/$', views.login, name="login"),
		url(r'^logout/$', views.logout, name="logout"),
		url(r'^disable/$', views.disable, name="disable"),
		)

createvm/urls.py
from django.conf.urls import patterns, url
from createvm import views


urlpatterns = patterns('',
		url(r'^login/$', views.login, name="login"),
		url(r'^index/$', views.index, name="index"),
		url(r'^logout/$', views.logout, name="logout"),
		url(r'^create/$', views.create, name="create"),
		url(r'^register/$', views.register, name="register"),
		url(r'^$', views.login, name="login"),
		
		)

openstack/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'openstack.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blockmanager/', include('blockmanager.urls', namespace='blockmanager')),
    url(r'^createvm/', include('createvm.urls', namespace='createvm')),
)

blockmanager/models.py
from django.db import models


# Create your models here.
class VM(models.Model):
    name = models.CharField(max_length=200)
    uuid = models.CharField(max_length=200)
    host = models.CharField(max_length=200)
    instance_id = models.CharField(max_length=200)
    ip = models.CharField(max_length=200)
    tenant_id = models.CharField(max_length=200)


class Storage(models.Model):
    vm = models.ForeignKey(VM, null=True)
    block_name = models.CharField(max_length=200)
    block_path = models.CharField(max_length=200)
    xml_name = models.CharField(max_length=200, null=True)
    xml_path = models.CharField(max_length=200, null=True)
    size = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    tenant_id = models.CharField(max_length=200, null=True)
    created_at = models.DateTimeField('block created', null=True)
    mounted_at = models.DateTimeField('block mounted', null=True)
    mountpoint = models.CharField(max_length=200, null=True)
    is_mounted = models.BooleanField(False)
    compute_group = models.CharField(max_length=200, null=True)
    used_size = models.CharField(max_length=200, null=True)
    uuid = models.CharField(max_length=200)


class Snapshot(models.Model):
    storage = models.ForeignKey(Storage)
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(max_length=200)
    snapshot_path = models.CharField(max_length=200)

blockmanager/views.py
#coding=utf-8
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.template import RequestContext
from django_ajax.decorators import ajax
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import string
import ansible.runner
import ConfigParser
import uuid
from blockmanager.models import VM, Storage, Snapshot
from lxml import etree
import random
import logging
import logging.config

from keystoneclient.auth.identity import v2
from keystoneclient import session
from novaclient import client
# Create your views here.


def login(request):
	try:
		if request.method == 'GET':
			return render(request,'blockmanager/login.html')
		configs = get_config()
		username = request.POST.get('username', None)
		password = request.POST.get('password', None)
		tenant_name = request.POST.get('tenant_name', None)

		auth = v2.Password(auth_url=configs['auth_url'], username=username, 
				password=password, tenant_name=tenant_name)
		sess = session.Session(auth=auth)
		nova = client.Client('2', session=sess)
		nova.servers.list()

		request.session['username'] = username
		request.session['password'] = password
		request.session['tenant_name'] = tenant_name
		return HttpResponseRedirect(reverse('blockmanager:index'))
	except Exception,e:
		name = request.session.get('username', 'root')
		logger = getLogger(name)
		logger.error(e)
		return HttpResponse(e)


def logout(request):
	try:
		request.session['username'] = None
		request.session['password'] = None
		request.session['tenant_name'] = None
		return HttpResponseRedirect(reverse('blockmanager:login'))
	except Exception,e:
		return HttpResponse(e)
	


def index(request):
	if request.session.get('username', None) == None:
		return HttpResponseRedirect(reverse('blockmanager:login'))
	configs = get_config()
	compute_group = configs['compute_group'].split(',')
	blocks = Storage.objects.all()
	paginator = Paginator(blocks, 10)
	page = request.GET.get('page');
	try:
		contacts = paginator.page(page)
	except PageNotAnInteger:
		contacts = paginator.page(1)
	except EmptyPage:
		contacts = paginator.page(paginator.num_pages)
	
	#return render(request, 'blockmanager/index.html', {'blocks': blocks})
	return render_to_response('blockmanager/index.html', {'contacts': contacts, 'compute_group':compute_group, 'username': request.session.get('username', None)}, context_instance=RequestContext(request))


@ajax
def get_vms(request):
	try:
		#验证input
		configs = get_config()
		ip = request.GET.get('the_ip')	
		name = request.GET.get('the_name')	
		if ip == '' and name == '':
			raise ValueError("argument error!")

		#通过nova api 取得nova servers list
		auth = v2.Password(auth_url=configs['auth_url'], username=configs['username'], 
				password=configs['password'], tenant_name=configs['tenant_name'])
		sess = session.Session(auth=auth)
		nova = client.Client('2', session=sess)
		vms = nova.servers
		vms = nova.servers.list()

		#得到符合要求的vms
		des_vms = []
		for vm in vms:
			if ip != '' and name != '':
				if vm.name == name and vm.networks[vm.networks.keys()[0]][0] == ip:
					des_vms.append(vm)
			elif ip != '':
				if vm.networks[vm.networks.keys()[0]][0] == ip:
					des_vms.append(vm)
			elif name != '':
				if vm.name == name:
					des_vms.append(vm)
					#return HttpResponse(vm.id)

		#生成html代码
		html_str = ''
		for vm in des_vms:
			html_str += '<tr>\n<td><input type="radio" name="xj-select" /></td>\n' \
					+ '<td>'+ vm.name + '</td>\t' + '<td>'+ vm.networks[vm.networks.keys()[0]][0] \
					+ '</td>\t' + '<td name="vm_uuid">' + vm.id +'</td></tr>' + '<input type="hidden" name="vm_uuid" value="' \
					+ vm.id + '"/>'


		return HttpResponse(html_str)

	except Exception,e:
		return HttpResponse(e)


def create_block(request):
	try:
		#验证input
		configs = get_config()
		block_name = request.POST['name']
		if block_name == '':
			raise ValueError('block name field is empty')

		size = request.POST['size']
		if(size == ''):
			raise ValueError('size field is empty')
		size = int(size)
		
		block_type = request.POST['type']
		if block_type == '':
			raise ValueError('block_type field is empty')
		if block_type not in configs['block_type']:
			raise ValueError('block type is undefined')

		compute_group = request.POST.get('compute_group')
		if compute_group == '':
			raise ValueError('compute group field is empty')
		
		#筛选出一个合适的host
		res = ansible.runner.Runner(module_name='ping', module_args='', pattern=compute_group, forks=10).run()
		compute_nodes = res['contacted']
		des_node = compute_nodes.keys()[int(random.random() * len(compute_nodes))]

		#得到block 的uuid, 并确保唯一性
		block_uuid = uuid.uuid1().hex

		#调用API，在筛选出的host上创建block
		if block_type == 'qcow2':
			args = '/usr/bin/qemu-img create -f qcow2 -o preallocation=metadata ' + configs['block_path'] + '/'  + block_uuid + '.qcow2 ' + str(size) + 'G'
		res = ansible.runner.Runner(module_name='shell', module_args=args, pattern=des_node, forks=10).run()
		if res['contacted'][des_node]['stderr'] != '':
			raise ValueError(res['contacted'][des_node]['stderr'])
		
		#如果成功就将此条数据，插入数据库，失败返回 ERROR
		block = Storage()
		block.block_name = block_name
		block.block_path = configs['block_path'] + '/' + block_uuid + '.' + block_type
		block.size = str(size) + 'G'
		block.type = block_type
		block.crated_at = timezone.now()
		block.is_mounted = False
		block.uuid = block_uuid
		block.compute_group = compute_group
		block.save()

		#log
		name = ''
		mesStr = request.session.get('username', 'root') + ' create block ' + str(size) + 'G named ' + block_name
		logger = getLogger(name)
		logger.info(mesStr)

		#success
		return HttpResponseRedirect(reverse('blockmanager:index'))
	except Exception, e:
		name = request.session.get('username', 'root')
		logger = getLogger(name)
		logger.error(e)
		return HttpResponse(e)

	
def import_block(request):
	try:
		#验证input
		configs = get_config()
		block_name = request.POST.get('name')
		compute_group = request.POST.get('compute_group')
		if block_name == '':
			raise ValueError('block name field is empty')
		if compute_group == '':
			raise ValueError('compute group field is empty')

		#筛选出一个合适的host
		res = ansible.runner.Runner(module_name='ping', module_args='', pattern=compute_group, forks=10).run()
		compute_nodes = res['contacted']
		des_node = compute_nodes.keys()[int(random.random() * len(compute_nodes))]
		#验证block 是否存在
		args = 'ls ' + configs['block_path'] + '/' + block_name
		res = ansible.runner.Runner(module_name='shell', module_args=args, pattern=des_node, forks=10).run()
		if res['contacted'][des_node]['stderr'] != '':
			raise ValueError('the block is not exist!')
		
		#如果已经导入过返回ERROR
		result = Storage.objects.filter(uuid=block_name)
		if len(result) > 0:
			raise ValueError('已经导入过，不能重复导入')

		#得到block 的虚拟大小、实际使用大小、类型
		args = '/usr/bin/qemu-img info ' + configs['block_path'] + '/' + block_name
		res = ansible.runner.Runner(module_name='shell', module_args=args, pattern=des_node, forks=10).run()
		d = {}
		for s in res['contacted'][des_node]['stdout'].split('\n'):
			item = s.split(":")
			if item[0].strip() == 'file format' or item[0].strip() == 'virtual size' \
					or item[0].strip() == 'disk size':
				key, value = item
				d[key.strip()] = value.strip()



		#如果成功就将此条数据，插入数据库，失败返回 ERROR
		block = Storage()
		block.block_name = block_name
		block.block_path = configs['block_path'] + '/' + block_name
		block.size = d['virtual size'].split('(')[0]
		block.type = d['file format']
		block.used_size = d['disk size']
		block.crated_at = timezone.now()
		block.is_mounted = False
		block.uuid = block_name
		block.compute_group = compute_group
		block.save()

		#log
		name = ''
		mesStr = request.session.get('username', 'root') + ' import block ' + d['virtual size'].split('(')[0] + ' named ' + block_name
		logger = getLogger(name)
		logger.info(mesStr)

		return HttpResponseRedirect(reverse('blockmanager:index'))

	except Exception, e:
		name = request.session.get('username', 'root')
		logger = getLogger(name)
		logger.error(e)
		return HttpResponse(e)


def search(request):
	try:
		if request.session.get('username', None) == None:
			return HttpResponseRedirect(reverse('blockmanager:login'))
		#根据条件，查询结果，失败返回 ERROR
		configs = get_config()
		compute_group = configs['compute_group'].split(',')
		block_name = request.POST.get('name')
		block_type = request.POST.get('type')
		vm_name = request.POST.get('vm_name')
		if block_name == '' and block_type == '' and vm_name == '':
			blocks = Storage.objects.all()
		elif block_name != '' and block_type!= '':
			blocks = Storage.objects.filter(block_name=block_name, type=block_type)
		elif block_name != '' and vm_name != '':
			blocks = Storage.objects.filter(block_name=block_name, vm__name=vm_name)
		elif block_type != '' and vm_name != '':
			blocks = Storage.objects.filter(type=block_type, vm__name=vm_name)
		elif block_name != '':
			blocks = Storage.objects.filter(block_name=block_name)
		elif block_type != '':
			blocks = Storage.objects.filter(type=block_type)
		elif vm_name != '':
			blocks = Storage.objects.filter(vm__name=vm_name)
		if block_name == None and block_type == None and vm_name == None:
			blocks = Storage.objects.all()

		#在template，显示结果
		paginator = Paginator(blocks, 10)
		page = request.GET.get('page');
		try:
			contacts = paginator.page(page)
		except PageNotAnInteger:
			contacts = paginator.page(1)
		except EmptyPage:
			contacts = paginator.page(paginator.num_pages)
	
	#return render(request, 'blockmanager/index.html', {'blocks': blocks})
		return render_to_response('blockmanager/index.html', {'contacts': contacts, 'compute_group': compute_group, 'username': request.session.get('username', None)}, context_instance=RequestContext(request))
	except Exception,e:
		return HttpResponse(e)
		
	

blockmanager/templates/blockmanager/index.html
<!doctype html>
{% csrf_token %}
<html>
 <head>
  <meta charset="UTF-8">
  <title>查询demo</title>
	
	<!--artDialog-->
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'blockmanager/css/artDialog/default.css'%}" />

	<link rel="stylesheet" href="{% static 'blockmanager/css/topo.css' %}" />

 </head>
 <body>
	
	<div class="header">
		<span class="h-title">块设备管理 v1.0</span>
	</div>
	
	<div class="wrap_div">
		<div class="content">
			
			<!--左边图标区-->
			<div class="topo-left">
				
				  <h4 class="icon-title">查询</h4>
				  <div class="lct-icon" style="display:block;">
					<ul class="left-menu">
						<li><a href="#">概况</a></li>
						<li class="active"><a href="#">实例</a></li>
						<li><a href="#">镜像</a></li>
						<li><a href="#">访问与安全</a></li>
					</ul>
				  </div>

				  <h4 class="icon-title">挂载</h4>
				  <div class="lct-icon">
					<ul class="left-menu">
						<li><a href="#">挂载</a></li>
					</ul>
				  </div>

				   <h4 class="icon-title">卸载</h4>
				  <div class="lct-icon">
					<ul class="left-menu">
						<li><a href="#">卸载</a></li>
					</ul>
				  </div>

			</div>
			<!--左边图标区-->

			<div  class="topo-right">
				
				<!--按钮区域-->
				<div class="right-title">
					<button id="new-btn" class="topo-btn new-btn">创建</button>
					<button id="prop-btn" class="topo-btn prop-btn">导入</button>

					<!--用户区-->
					<div class="user-area">
						<a href="#" title="admin"><span class="top-user">{{ username }}</span></a>
						<a href="{% url 'blockmanager:logout' %}" title="登出"><span class="user-out">登出</span></a>
					</div>
				</div>
				<!--按钮区域-->
				
				<div class="right-content">

					<h1>实例</h1>
					
					<!--搜索区域-->
					<form action="{% url 'blockmanager:search' %}" method="post">
			{% csrf_token %}
						<div class="search-area">
							<div>
								<span>名称：<input type="text" name="name" value="" /></span>
								<span>虚机名称：<input type="text" name="vm_name" value="" /></span>
								<span>格式：<select name="type"><option></option><option>qcow2</option></select></span>
								<span><input type="submit" class="search_button" value="查询" /></span>
							</div>				
						</div>
					</form>
					<!--搜索区域-->
					
					<div id="eq-area">

						<table class="list-table" cellspacing=0 cellpadding=0>
							<thead>
								<tr>
									<th><input type="checkbox" name="allcheck" /></th>
									<th>名称</th>
									<th>大小(G)</th>
									<th>格式</th>
									<th>云主机</th>
									<th>挂载点</th>
									<th>block id</th>
									<th>tenant id</th>
									<th>操作</th>
								</tr>
							</thead>
							<tbody>
							{% for block in contacts %}
								<tr>
									<td><input type="checkbox" /></td>
									<td>{{ block.block_name }}</td>
									<td>{{ block.size }}</td>
									<td>{{ block.type }}</td>
									{% if block.is_mounted %}
									<td>{{ block.vm.name}}::{{ block.vm.uuid }}</td>
									{% else %}
									<td>NULL</td>
									{% endif %}
									<td>{{ block.mountpoint }}</td>
									<td>{{ block.uuid }}</td>
									<td>{{ block.tenant_id }}</td>
									<td>
										<select class="action-select">
											<option>选择操作</option>
											<option value="1">挂载</option>
											<option value="2">卸载</option>
											<option value="3">删除</option>
											<option value="4">disable</option>
										</select>
										<input class="list-id" type="hidden" value="{{ block.id }}" />
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					

						<div class="search_page">
							<span>
								{% if contacts.has_previous %}
								<a href="{% url 'blockmanager:index'%}?page={{ contacts.previous_page_number }}" style='text-decoration:underline'>previous</a>
								{% endif %}
								Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}
								{% if contacts.has_next %}
								<a href="{% url 'blockmanager:index' %}?page={{ contacts.next_page_number }}" style='text-decoration:underline'>next</a>
								{% endif %}
							</span>
						</div>

					</div>

				</div>

			</div>

			<div class="clear"></div>
		</div>
	</div>

	</div>

	<!--弹窗-->

	<!--创建-->
	<div id="new-win" class="modal">
		<form id="new-form" action="{% url 'blockmanager:create_block' %}" method="post">
			{% csrf_token %}
			<table class="moban-table">
				<tr>
					<td class="table-tab">名称</td>
					<td><input type="text" name="name" value="" /></td>
				</tr>
				<tr>
					<td class="table-tab">大小(G)</td>
					<td><input type="text" name="size" value="" /></td>
				</tr>
				<tr>
					<td class="table-tab">格式</td>
					<td>
						<select name="type">
							<option>qcow2</option>
						</select>
					</td>
				</tr>
				<tr>
					<td class="table-tab">节点集群</td>
					<td>
						<select name="compute_group">
							{% for group in compute_group %}
							<option>{{ group }}</option>
							{% endfor %}
						</select>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<!--创建-->

	<!--导入-->
	<div id="prop-win" class="modal">
		<form id="prop-form" action="{% url 'blockmanager:import' %}" method="post">
			{% csrf_token %}
			<table class="moban-table">
				<tr>
					<td class="table-tab">文件名称</td>
					<td><input type="text" name="name" value="" /></td>
				</tr>
				<tr>
					<td class="table-tab">节点集群</td>
					<td>
						<select name="compute_group">
							{% for group in compute_group %}
							<option>{{ group }}</option>
							{% endfor %}
						</select>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<!--导入-->

	<!--挂载-->
	<div id="location-win" class="modal">

		<!--搜索区域-->
		<div class="search-area">
			<div>
				<span>名称：<input id="gz-s-name" type="text" value="" /></span>
				<span>IP地址：<input id="gz-s-ip" type="text" value="" /></span>
				<span><input id="gz-search" type="button" class="search_button" value="查询" /></span>
			</div>				
		</div>
		<!--搜索区域-->
		
		<form  id="action-form" action="{% url 'blockmanager:mount' %}" method="post">
			{% csrf_token %}
			<input id="gz-list-id" type="hidden" name='block_id' value=""/>
			<table class="list-table" cellspacing=0 cellpadding=0>
				<thead>
					<tr>
						<th></th>
						<th>名称</th>
						<th>IP</th>
						<th>uuid</th>
					</tr>
				</thead>
				<tbody id="vm-list">
				</tbody>
			</table>
		</form>
		</div>

	</div>
	<!--挂载-->

	<!--弹窗-->
	
	<!--jquery-->
	<script src="{% static 'blockmanager/js/jquery-1.8.0.min.js' %}" ></script>
	
	<!--jqueryui-->
	<script src="{% static 'blockmanager/js/jqueryui/jquery-ui-1.10.4.custom.js' %}" ></script>

	<!--artDialog-->
	<script src="{% static 'blockmanager/js/artDialog/artDialog.js' %}"></script>

	<script src="{% static 'blockmanager/js/mine.js' %}"></script>

 </body>
</html>

blockmanager/templates/blockmanager/login.html
<html>
	<form action="{% url 'blockmanager:login' %}" method="post"> {% csrf_token %}
		username: <input name="username" type="text"/><p/>
		password: <input name="password" type="text"/><p/>
		tenant_name: <input name="tenant_name" type="text"/><p/>
		<input type="submit">
	</form>
</html>