createvm/urls.py
from django.conf.urls import patterns, url
from createvm import views


urlpatterns = patterns('',
		url(r'^login/$', views.login, name="login"),
		url(r'^index/$', views.index, name="index"),
		url(r'^logout/$', views.logout, name="logout"),
		url(r'^create/$', views.create, name="create"),
		url(r'^register/$', views.register, name="register"),
		url(r'^$', views.login, name="login"),
		
		)

openstack/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'openstack.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blockmanager/', include('blockmanager.urls', namespace='blockmanager')),
    url(r'^createvm/', include('createvm.urls', namespace='createvm')),
)

createvm/models.py
from django.db import models

# Create your models here.

class Member(models.Model):
	name = models.CharField(max_length=200)
	is_active = models.BooleanField(False)


class Vm(models.Model):
	member = models.ForeignKey(Member, null=True)
	name = models.CharField(max_length=200)
	os = models.CharField(max_length=200)
	create_at = models.DateTimeField('vm created', null=True)
	cpuAndRam = models.CharField(max_length=200)


class Network(models.Model):
	member = models.ForeignKey(Member, null=True)
	name = models.CharField(max_length=200)
	ip = models.CharField(max_length=200)
	netmask = models.CharField(max_length=200)
	vlan_id = models.CharField(max_length=200)
	start = models.CharField(max_length=200)
	end = models.CharField(max_length=200)
	is_used = models.BooleanField(False)

createvm/views.py
#coding=utf-8
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.template import RequestContext
from django_ajax.decorators import ajax
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from blockmanager.views import get_config
from createvm.models import Member, Vm, Network

import string
import ansible.runner
import ConfigParser
import uuid
from lxml import etree
import random
import logging
import logging.config
import os as python_os

from keystoneclient.auth.identity import v2
from keystoneclient import session
from novaclient import client
from keystoneclient.v2_0 import client as keystoneClient
# Create your views here.

# Create your views here.


def login(request):
	try:
		if request.session.get('username', None) != None:
			return HttpResponseRedirect(reverse('createvm:index'))
		if request.method == 'GET':
			return render(request,'createvm/login.html')
		#判断验证码
		check_code = request.POST.get('check_code', None)
		code = request.POST.get('code', None)
		if check_code.lower() != code.lower():
			raise ValueError('验证码错误')

		username = request.POST.get('username', None)
		password = request.POST.get('password', None)
		if username == None or password == None:
			raise ValueError('input lack')
		tenant_name = username
		configs = get_config()
		auth_url = configs['auth_url'] 

		auth = v2.Password(auth_url=auth_url, username=username, 
				password=password, tenant_name=tenant_name)
		sess = session.Session(auth=auth)
		nova = client.Client('2', session=sess)
		nova.servers.list()

		request.session['username'] = username
		request.session['password'] = password
		request.session['tenant_name'] = tenant_name
		request.session['auth_url'] = auth_url

		return HttpResponseRedirect(reverse('createvm:index'))
	except Exception,e:
		name = request.session.get('username', 'root')
		logger = getLogger(name)
		logger.error(e)
		return HttpResponse(e)


def register(request):
	try:
		if request.session.get('username', None) != None:
			return HttpResponseRedirect(reverse('createvm:index'))
		if request.method == 'GET':
			return render(request, 'createvm/register.html')
		
		if request.method == 'POST':
			check_code = request.POST.get('check_code', None)
			code = request.POST.get('code', None)
			if code.lower() != check_code.lower():
				raise ValueError('验证码错误')

			username = request.POST.get('username', None)
			password = request.POST.get('password', None)
			check_password = request.POST.get('check_password', None)
			email = request.POST.get('email', None)
			code = request.POST.get('code', None)
			check_code = request.POST.get('check_code', None)
			if username == '' or password == '' or check_password == '' or email == '' or code == '':
				raise ValueError('缺少输入')


			if password != check_password:
				raise ValueError('两次密码不一样')

			configs = get_config()
			keystone = keystoneClient.Client(auth_url=configs['auth_url'], username=configs['username'],
						password=configs['password'], tenant_name=configs['tenant_name'])
			keystone.tenants.create(tenant_name=username,
										description=username + " Tenant", enabled=True)
			tenants = keystone.tenants.list()
			my_tenant = [x for x in tenants if x.name==username][0]
			my_user = keystone.users.create(name=username,
							password=password, tenant_id=my_tenant.id, email=email)

			#用户添加amdin 角色
			admin_role = None
			for r in keystone.roles.list():
				if r.name == "admin":
					admin_role = r

			keystone.roles.add_user_role(my_user, admin_role, my_tenant)

			mem = Member()
			mem.name = username
			mem.is_active = False
			mem.save()

			return HttpResponseRedirect(reverse('createvm:login'))

	except Exception,e:
		return HttpResponse(e)



def logout(request):
	try:
		request.session['username'] = None
		request.session['password'] = None
		request.session['tenant_name'] = None
		return HttpResponseRedirect(reverse('createvm:login'))
	except Exception,e:
		return HttpResponse(e)
	


def index(request):
	try:
		if request.session.get('username', None) == None:
			return HttpResponseRedirect(reverse('createvm:login'))

		username = request.session['username']
		password = request.session['password']
		tenant_name = request.session['tenant_name']
		auth_url = request.session['auth_url']
		auth = v2.Password(auth_url=auth_url, username=username, 
					password=password, tenant_name=tenant_name)
		sess = session.Session(auth=auth)
		nova = client.Client('2', session=sess)
		vms = []
		for ins in nova.servers.list():
			flavor_id = ins.flavor.get('id')
			image_id = ins.image.get('id')
			flavor = nova.flavors.find(id=flavor_id)
			image = nova.images.find(id=image_id)
			if ins.status == 'ACTIVE':
				vnc_url = ins.get_vnc_console('novnc').get('console').get('url')
			else:
				vnc_url = ''
			vm = {'vcups':flavor.vcpus, 'ram':flavor.ram, 'os': image.name, 'name': ins.name, 
					'status':ins.status, 'vnc_url':vnc_url}
			vms.append(vm)

		return render(request,'createvm/index.html', {'vms':vms, 'username':username})

	except Exception, e:
		return HttpResponse(e)


def create(request):
	try:
		if request.session.get('username', None) == None:
			return HttpResponseRedirect(reverse('createvm:login'))
		username = request.session['username']
		password = request.session['password']
		tenant_name = request.session['tenant_name']
		auth_url = request.session['auth_url']
		auth = v2.Password(auth_url=auth_url, username=username, 
					password=password, tenant_name=tenant_name)
		sess = session.Session(auth=auth)
		nova = client.Client('2', session=sess)
		if request.method == 'GET':
			images = nova.images.list()
			return render(request,'createvm/create.html', {'images': images, 'username':username})

		if request.method == 'POST':
			ram = request.POST.get('ram')
			if ram == None:
				raise ValueError('ram is None')
			if 'G' in ram:
				ram = int(ram[:-1]) * 1024
			else:
				ram = int(ram[:-1])
			vcpus = request.POST.get('vcpus')
			if vcpus == None:
				raise ValueError('ram is None')
			vcpus = int(vcpus)
			os = request.POST.get('os')
			if nova.images.find(name=os) == None:
				raise ValueError('choose os')
			vm_name = request.POST.get('vm_name')
			if vm_name == None or vm_name == '':
				raise ValueError('enter a vm name')
			if os == None:
				raise ValueError('choose os')
			number = request.POST.get('number')
			if number == None or number == '0':
				raise ValueError('vm number is error')
			number = int(number)

			flavor = nova.flavors.find(vcpus=vcpus, ram=ram)
			image = nova.images.find(name=os)
			#nics = [{'net-id': nova.networks.list()[0].id}]

			#得到一个合适的网络
			no = int(random.random()*len(Network.objects.filter(is_used=False)))
			net = Network.objects.filter(is_used=False)[no]
			ip = net.ip
			netmask = net.netmask
			vlan_id = net.vlan_id
			start = net.start
			end = net.end


			#创建网络
			m = Member.objects.get(name=username)
			net_name = username + "_net"
			python_os.environ['OS_USERNAME'] = username;
			python_os.environ['OS_PASSWORD'] = password;
			python_os.environ['OS_AUTH_URL'] = auth_url;
			python_os.environ['OS_TENANT_NAME'] = tenant_name;
			if m.is_active == False:
				cmd = './createvm/cn.sh ' + net_name + ' ' + ip + ' ' + netmask + ' ' + vlan_id + ' ' + start + ' ' + end
				n = python_os.system(cmd)
				if (n >> 8) != 0:
					raise ValueError("网络创建失败")
				m.is_active = True
				m.save()
				net.member_id = m.id
				net.name = net_name
				net.is_used = True
				net.save()

			#得到目标网络
			desNet = None
			for net in nova.networks.list():
				if net.human_id == net_name:
					desNet = net

			if desNet == None:
				raise ValueError("没有找到网络")
			nics = [{'net-id': desNet.id}]

			for i in range(number):
				nova.servers.create(vm_name, flavor=flavor.id, image=image.id, nics=nics)
			return HttpResponseRedirect(reverse('createvm:index'))
	except Exception, e:
		return HttpResponse(e)


def getLogger(name):
	try:
		if name == '' or name == None:
			name = ''

		logging.config.fileConfig('blockmanager/log.conf')
		logger = logging.getLogger(name)
		return logger
	except Exception,e:
		return HttpResponse(e)

createvm/templates/createvm/create.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>沪正软件</title>
</head>
	
	<meta charset="utf-8" />
	<!--style-->
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'createvm/css/black.css' %}" />
	<!--style-->

	<link rel="stylesheet" href="{% static 'createvm/css/product.css' %}" />
	<link rel="stylesheet" href="{% static 'createvm/css/select/dropkick.css' %}" type="text/css">

<body>
	
	<!--header-->
	<div class="header">
		
		<!--topbar-->
		<div class="top-bar">
			<ul>
				<li>欢迎：<a href="login.html">沪正登录</a></li>
				<li>|</li>
				<li><a href="register.html">注册</a></li>
			</ul>
		</div>
		<!--topbar-->
		
		<!--topmenu-->
		<div class="topmenu">
			<a class="logo" href="{% url 'createvm:index' %}">
				<img src="{% static 'createvm/images/header/logo.png' %}" />
			</a>
			<ul>
				<li><a href="index.html">首页</a></li>
				<li>
					<a href="javascript:;">产品</a>
					<ul class="drop-menu">
						<li><a href="xnlogin.html">沪正虚拟服务器</a></li>
					</ul>
				</li>
				<li><a href="hire.html">联系我们</a></li>
				<li><a href="hire.html">加入我们</a></li>
			</ul>
		</div>
		<!--topmenu-->

	</div>
	<!--header-->
	
	<!--content-->
	<div class="content">
		
		<div class="content-container" style="width:1076px;">
			
			<!--右边部分-->
			<!--右边部分-->

			<!--左边部分-->
			<div class="main" style="min-height:492px;">
				
				<div class="page-tab">
					<ul>
						<li class="current">
							<a href="javascript:;">沪正虚拟服务器</a>
						</li>
					</ul>
				</div>

				<div class="page-buy">
					
					<form action="{% url 'createvm:create'%}" method="post">{% csrf_token %}
						<div class="form" style="padding: 10px 0px 0px;">
							<div class="row">
								<label class="row-name">虚机名称：</label>
									<div class="column">																													<input class="hz-input" name='vm_name' style="width:195px;text-align:left;" type="text" value="" />
									</div>																														</div>
								<div class="row">
									<label class="row-name">CPU：</label>
									<div class="column">

										<span class="hz-radio hz-cpu">
											<a class="unit current" tocpu="1" showm="m1">1核</a>
											<a class="unit" tocpu="2" showm="m2">2核</a>
											<a class="unit" tocpu="4" showm="m3">4核</a>
											<a class="unit" tocpu="8" showm="m4">8核</a>
											<a class="unit" tocpu="16" showm="m5">16核</a>
										</span>

										<input id="hz-cpu" name='vcpus' type="hidden" value="1" />

									</div>
								</div>
	
								<div class="row">
									<label class="row-name">内存：</label>
									<div class="column">

										<span id="m1" class="hz-radio hz-memory" style="display:inline-block;">
											<a class="unit current" tomemory="512M">512MB</a>
											<a class="unit" tomemory="1G">1GB</a>
											<a class="unit" tomemory="2G">2GB</a>
											<a class="unit" tomemory="5G">4GB</a>
											<a class="unit" tomemory="8G">8GB</a>
										</span>

										<span id="m2" class="hz-radio hz-memory">
											<a class="unit current" tomemory="2G">2GB</a>
											<a class="unit" tomemory="4G">4GB</a>
											<a class="unit" tomemory="8G">8GB</a>
											<a class="unit" tomemory="16G">16GB</a>
										</span>

										<span id="m3" class="hz-radio hz-memory">
											<a class="unit current" tomemory="4">4GB</a>
											<a class="unit" tomemory="8G">8GB</a>
											<a class="unit" tomemory="16G">16GB</a>
											<a class="unit" tomemory="32G">32GB</a>
										</span>

										<span id="m4" class="hz-radio hz-memory">
											<a class="unit current" tomemory="8">8GB</a>
											<a class="unit" tomemory="16G">16GB</a>
											<a class="unit" tomemory="32G">32GB</a>
											<a class="unit" tomemory="64G">64GB</a>
										</span>

										<span id="m5" class="hz-radio hz-memory">
											<a class="unit current" tomemory="16">16GB</a>
											<a class="unit" tomemory="32G">32GB</a>
											<a class="unit" tomemory="64G">64GB</a>
										</span>

										<input id="hz-memory" name='ram' type="hidden" value="512M" />

										<div class="tip-row">
											<span>为了保证良好的性能体验，推荐使用双核4G</span>
										</div>

									</div>
								</div>
	
								<div class="row">
									<label class="row-name">镜像：</label>
									<div class="column" style="line-height:22px;">

										<select id="sys-change" name="os" class="change">
											<option toversion="v0">选择操作系统</option>
											{% for img in images%}
											<option value="{{ img.name }}" toversion="v1">{{ img.name }}</option>
											{% endfor %}
										</select>

								</div>
	
								<!--<div class="row">
									<label class="row-name">购买时间：</label>
									<div id="column1" class="column">
										<span class="hz-slider">
											<div id="range1" class="range">
												<span class="block mm">
													<div>
														<span>1</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>2</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>3</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>4</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>5</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>6</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>7</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>8</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>9</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>10</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>11</span>
													</div>
												</span>
												<span class="block mm">
													<div>
														<span>12 月</span>
													</div>
												</span>
												<span class="block yy">
													<div>
														<span>2年</span>
													</div>
												</span>
												<span class="block yy">
													<div style="border:0;padding:0;">
														<span>3年</span>
													</div>
												</span>
												
												<div class="container" style="width:37px;">
													<div class="current">
														<span class="block mm">
															<div>
																<span>1</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>2</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>3</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>4</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>5</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>6</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>7</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>8</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>9</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>10</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>11</span>
															</div>
														</span>
														<span class="block mm">
															<div>
																<span>12</span>
															</div>
														</span>
														<span class="block yy">
															<div style="border:0;padding:0;">
																<span>3年</span>
															</div>
														</span>
													</div>
												</div>
												<a id="drag1" class="drag" style="left:30px;" href="javascript:;"></a>
											</div>
										</span>
									</div>
								</div>-->
	
								<div class="row" style="overflow:hidden;">
									<label class="row-name">购买数量：</label>
									<div class="column">
										<input class="hz-input" name='number' type="text" value="1" />
										台
									</div>
								</div>
	
								<div class="button-row">
									<button class="add-order">创建</button>
								</div>
	
								<div class="hz-submit"></div>
	
						</div>
					</form>
                    
				</div>

			</div>
			<!--左边部分-->
		
		</div>

	</div>
	<!--content-->
	
	<!--footer-->
	<div class="footer">
		沪ICP备 12042907
	</div>
	<!--footer-->

	<script type="text/javascript" src="{% static 'createvm/js/jquery-1.11.1.js' %}"></script>

	<script type="text/javascript" src="{% static 'createvm/js/jquery-ui-1.10.4.custom.js' %}"></script>

	<script type="text/javascript" src="{% static 'createvm/js/index.js' %}"></script>

	<script type="text/javascript" src="{% static 'createvm/js/select/jquery.dropkick.js' %}"></script>

	<script>
	
		$(function(){
			
			$('.change').dropkick();

			$( "#drag1" ).draggable({ 
				containment: "#range1",
				axis: "x",
				drag: function(event,ui){
					var temp = $(this).css("left");
					$(this).prev(".container").css("width",temp);
				},
				stop:function(event,ui){
					var finalleft = parseInt($(this).css("left"));
				}
			
			});

			$( "#drag2" ).draggable({ 
				containment: "#range2",
				axis: "x",
				drag: function(event,ui){
					var temp = $(this).css("left");
					$(this).prev(".container").css("width",temp);

					var finalleft = parseInt($(this).css("left"));
					var inputM = parseInt(finalleft*100/482);
					$("#Minput").val(inputM);

				}
			
			});

		});

	</script>

</body>
</html>

createvm/templates/createvm/index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>沪正软件</title>
</head>
	
	<meta charset="utf-8" />
	<!--style-->
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'createvm/css/black.css' %}" />
	<!--style-->

	<link rel="stylesheet" href="{% static 'createvm/css/product.css' %}" />
	<link rel="stylesheet" href="{% static 'createvm/css/select/dropkick.css' %}" type="text/css">

<body>
	
	<!--header-->
	<div class="header">
		
		<!--topbar-->
		<div class="top-bar">
			<ul>
				<li>欢迎：<a href="#">{{ username }}</a></li>
				<li>|</li>
				<li><a href="{% url 'createvm:logout' %}">登出</a></li>
			</ul>
		</div>
		<!--topbar-->
		
		<!--topmenu-->
		<div class="topmenu">
			<a class="logo" href="{% url 'createvm:index' %}">
				<img src="{% static 'createvm/images/header/logo.png' %}" />
			</a>
			<h1>虚机管理系统</h1>
		</div>
		<!--topmenu-->

	</div>
	<!--header-->
	
	<!--content-->
	<div class="content">

		<div class="content-container" style="margin-top:10px;min-height:490px;">
			
			<div>
				<a class="edit-btn" href="{% url 'createvm:create' %}">新建虚机</a>
			</div>

			 <!--我的应用4-->
			<div class="page-buy page-list">
				
				<table class="myxntable" style="margin-top:15px;">
				<thead>
					<tr>
						<th>虚机名称</th>
						<th>CPU</th>
						<th>内存</th>
						<th>操作系统</th>
						<th>运行状态</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
				{% for vm in vms %}
					<tr>
						<td>{{ vm.name }}</td>
						<td>{{ vm.vcups }}</td>
						<td>{{ vm.ram }}M</td>
						<td>{{ vm.os }}</td>
						<td>{{ vm.status }}</td>
						<td>
							{% if vm.vnc_url %}
							<a class="edit-btn" style="margin-top:3px;" href="{{ vm.vnc_url }}">console</a>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
            
            </div>
            <!--我的应用4-->
		
		</div>

	</div>
	<!--content-->
	
	<!--footer-->
	<div class="footer">
		沪ICP备 12042907
	</div>
	<!--footer-->

	<script type="text/javascript" src="js/jquery-1.11.1.js"></script>

	<script type="text/javascript" src="js/jquery-ui-1.10.4.custom.js"></script>

	<script type="text/javascript" src="js/index.js"></script>

	<script type="text/javascript" src="js/select/jquery.dropkick.js"></script>

	<script>
	
		$(function(){
			
			$('.change').dropkick();

			$( "#drag1" ).draggable({ 
				containment: "#range1",
				axis: "x",
				drag: function(event,ui){
					var temp = $(this).css("left");
					$(this).prev(".container").css("width",temp);
				},
				stop:function(event,ui){
					var finalleft = parseInt($(this).css("left"));
				}
			
			});

			$( "#drag2" ).draggable({ 
				containment: "#range2",
				axis: "x",
				drag: function(event,ui){
					var temp = $(this).css("left");
					$(this).prev(".container").css("width",temp);

					var finalleft = parseInt($(this).css("left"));
					var inputM = parseInt(finalleft*100/522);
					$("#Minput").val(inputM);

				}
			
			});

			$(".unit").click(function(){
				
				$(this).addClass("current");
				$(this).siblings(".unit").removeClass("current");


			});

			$(".myxntable tbody tr:even").css("background-color", "#f9f9f9");

		});

	</script>

</body>
</html>

createvm/templates/createvm/login.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>沪正软件虚机管理</title>
</head>
	
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'createvm/css/login.css' %}" />


<body onload="createCode()">
	
	<div class="login">
		
		<div class="modal-header">
			<h3>登录</h3>
		</div>

		<form action="{% url 'createvm:login' %}" method="post">{% csrf_token %}

			<div class="modal-body">
				<div class="form-group">
					<label class="control-label">用户名</label>
					<div class="control-div">
						<input name="username" type="text" value="" />
					</div>
				</div>
				<div class="form-group">
					<label class="control-label">密码</label>
					<div class="control-div">
						<input name="password" type="password" value="" />
					</div>
				</div>
				<div class="form-group">
					<label class="control-label">验证码</label>
					<div class="control-div">
						<input name="code" type="text" style="width:40%;" value="" />
						<input id="checkCode" name="check_code" type="text" onclick="createCode()" readonly="readonly" style="width: 80px" />
						<a href="#" class="checkcode">看不清，换一张</a>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				<button class="enter-btn" type="submit">登入</button>
				<a class="reg-btn" href="{% url 'createvm:register' %}">注册</a>
			<div>

		</form>
		
	</div>

	<script type="text/javascript" src="{% static 'createvm/js/code.js' %}"></script>

</body>
</html>

createvm/templates/createvm/register.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>沪正软件</title>
</head>
	
	<meta charset="utf-8" />
	{% load staticfiles %}

	<link rel="stylesheet" href="{% static 'createvm/css/register.css' %}" />

<body onload="createCode()">
	
    <!--顶部-->
	<div class="header-container">
    
		<div class="header">

			<a class="logo" href="{createvm:login}"></a>

			<span class="header-title">帐号注册</span>

		</div>
        
	</div>
    <!--顶部-->
	
    <!--内容-->
	<div class="content-container">
		
		<div class="content">

			<div class="regist-module" style="margin-bottom:100px; margin-top:5px">
				
                <!--注册信息-->
				<div class="regist-wrap">
					<form action="{% url 'createvm:register' %}" method="post">{% csrf_token %}
						<table class="regist-table">
							<tbody>
								<tr>
									<td class="fm-label">
										<div class="fm-relative">
											<span class="regist-icon regist-email"></span>
											<label>
												<span class="noempty">*</span>
												用户名称：
											</label>
										</div>
									</td>
									<td class="fm-field" width="300">
										
										<input name="username" class="fm-text" value="" type="text" />

									</td>
								</tr>
								<tr>
									<td class="fm-label">
										<label>
											<span class="noempty">*</span>
											登录密码：
										</label>
									</td>
									<td class="fm-field">
										<input name="password" class="fm-text" value="" type="password" />
									</td>
								</tr>
								<tr>
									<td class="fm-label">
										<label>
											<span class="noempty">*</span>
											确认登录密码：
										</label>
									</td>
									<td class="fm-field">
										
										<input name="check_password" class="fm-text" value="" type="password" />

									</td>
								</tr>
								<tr>
									<td></td>
									<td>
										<div class="fm-split">电子邮箱(电子邮箱为安全信息，不作登录使用)</div>
									</td>
								</tr>
								<tr>
									<td class="fm-label">
										<div class="fm-relative">
											<span class="regist-icon regist-mobile"></span>
											<label>
												<span class="noempty">*</span>
												电子邮箱：
											</label>
										</div>
									</td>
									<td class="fm-field">
										<input name="email" class="fm-text" value="" type="text" />
									</td>
								</tr>
								<tr>
									<td class="fm-label">
										<label>
											<span class="noempty">*</span>
											图片验证码：
										</label>
									</td>
									<td class="fm-field">
										
										
										<input name="code" class="fm-text" style="width:48px;" value=""  type="text" />
										<input name="check_code" id="checkCode" type="text" onclick="createCode()" readonly="readonly" style="width: 80px" />
										<a href="#" class="checkcode">看不清，换一张</a>

									</td>
								</tr>
								<tr>
									<td></td>
									<td class="fm-field">	
										<input value="同意并注册" class="fm-submit" type="submit" />
										<a class="rt-btn" href="javascript:window.history.back();">返回登录</a>
									</td>
								</tr>
							</tbody>
						</table>
					</form>
				</div>
                <!--注册信息-->
                
				<!--注册说明-->
                <div class="regist-extra">
					<p>沪正虚拟服务器，公共开放的云计算服务平台！</p>
					<p>产品稳定、数据可靠；</p>
					<p>弹性伸缩、按需付费！</p>
				</div>
				<!--注册说明-->

			</div>
		
		</div>

	</div>
    <!--内容-->
    
    <!--底部-->
    <div class="footer-container">
    	
		<div class="footer">
			<div class="footer-content">
				<p>沪ICP备 12042907</p>
			</div>
		</div>

    </div>
    <!--底部-->

	<script type="text/javascript" src="{% static 'createvm/js/code.js' %}"></script>	

</body>
</html>